// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojtjyexxsoxjikbwtlfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdGp5ZXh4c294amlrYnd0bGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjIwNTYsImV4cCI6MjA2MDE5ODA1Nn0.NWYW4yWv7OMH0UQqpeMu7lGJjM1hndU_1uD2pMS5RyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);